(deftheme nier
  "Created 2024-02-03.")

(defun true-color-p ()
  (or (display-graphic-p)
    (= (tty-display-color-cells) 16777216)))

(defconst kanagawa-dark-palette
  `((ng1       ,(if (true-color-p) "#404040" "#585858"))
     (ng2       ,(if (true-color-p) "#787466" "#585858"))
     (ng3       ,(if (true-color-p) "#686458" "#303030"))
     (ng4       ,(if (true-color-p) "#5e6666" "#303030"))
     (ng5       ,(if (true-color-p) "#5e6666" "#303030"))
     ))

(custom-theme-set-faces
 'nier
 '(highlight ((t (:background "#999482"))))
 '(cursor ((t (:background "#727969"))))
 '(custom-comment ((t (:foreground "#A9A491"))))
 '(font-lock-comment-face ((t (:foreground "#A9A491"))))
 '(mode-line ((t (:background "#686458" :foreground "#dad4bb"))))
 '(fringe ((t (:background "#dad4bb"))))
 '(widget-field ((t (:box (:line-width (1 . -1) :color "gray80") :background "#f4f0e1" :extend t))))
 '(custom-button ((t (:box (:line-width (2 . 2) :style released-button) :foreground "#404040" :background "#f4f0e1"))))
 '(region ((t (:extend t :background "#727969"))))
 '(font-lock-function-name-face ((t (:foreground "#076678"))))
 '(font-lock-string-face ((t (:foreground "#427b58"))))
 '(font-lock-keyword-face ((t (:foreground "#b26f5f"))))
 '(link ((t (:underline t :foreground "#3ba99f"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#cac4ad" :foreground "grey20" :weight light))))
 '(font-lock-variable-name-face ((t (:foreground "#5e6666"))))
 '(default ((t (:background "#dad4bb" :foreground "#404040"))))
 '(font-lock-builtin-face ((t (:foreground "#787466"))))
 '(secondary-selection ((t (:extend t :background "#f9f5d7"))))
 '(popup-face ((t (:inherit default :background "#f9f5d7" :foreground "black"))))
 '(font-lock-type-face ((t (:foreground "#9f8962"))))
 '(custom-button-mouse ((t (:background "f9f5d7" :foreground "black" :box (:line-width (2 . 2) :style released-button)))))
 '(custom-button-pressed ((t (:box (:line-width (2 . 2) :style pressed-button) :foreground "black" :background "#f9f5d7"))))
 '(diff-added ((t (:inherit diff-changed :extend t :background "#727b59"))))
 '(diff-removed ((t (:inherit diff-changed :extend t :background "#cd664d"))))
 '(diff-changed ((t (:extend t :background "#bdae93"))))
 '(diff-hl-change ((t (:background "#686458" :foreground "#b4af9a"))))
 '(error ((t (:foreground "#9d0006" :weight bold))))
 '(match ((t (:background "#b4af9a"))))
 '(isearch ((t (:background "#8f3f71" :foreground "#f9f5d7"))))
 '(custom-set ((t (:background "#f9f5d7" :foreground "#282828"))))
 '(success ((t (:foreground "#727b59" :weight bold))))
  '(lazy-highlight ((t (:background "#5e6666" :distant-foreground "black"))))
  '(show-paren-match ((t (:background "#b4af9a"))))
  '(telega-msg-heading ((t (:background "#b9b49f"))))
  '(org-todo ((t (:forground "#b26f5f"))))
  '(corfu-default ((t (:background "#cac4ad"))))
  '(corfu-border ((t (:background "#a9a491"))))
  '(corfu-current ((t (:foreground "#f9f5d7" :background "#787466"))))
  '(completions-common-part ((t (:foreground "#076678"))))
  '(orderless-match-face-0 ((t (:weight bold :foreground "#076678"))))
  '(orderless-match-face-1 ((t (:weight bold :foreground "#8f3f71"))))
  '(orderless-match-face-2 ((t (:weight bold :foreground "#427b58"))))
  ;; '(message-header-xheader ((t (:foreground "#f9f5d7" :background "#686458"))))
  ;; '(comint-highlight-prompt ((t (:foreground "#f9f5d7" :background "#686458"))))
  '(minibuffer-prompt ((t (:foreground "#f9f5d7" :background "#686458"))))
  )

(provide-theme 'nier)
